### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by ddliu** [anyfs/anyfs#6]

**Comment by denjello** [comment]
![universal_converter_box](https://cloud.githubusercontent.com/assets/6129121/7323626/4d2d5dec-eab0-11e4-8a19-e944cafe9d63.png)

https://xkcd.com/1406/

**Comment by ddliu** [comment]
Very fanny! 

But seems complicated, a simple small logo is preferred.

**Comment by denjello** [comment]
That was just a joke, but if this is still needed, I have a few ideas.

**Comment by denjello** [comment]
Here is one sketch -> it is a play-once gif.
cc-by

![anyfs_expletussans_border](https://cloud.githubusercontent.com/assets/6129121/7332505/4e2ebd7a-eb42-11e4-9d91-8458d349945f.gif)

**Comment by denjello** [comment]
See here:

https://github.com/denjello/anyfs/tree/master/lib/assets

**Comment by yazhouzou** [comment]
@denjello That is interesting~   Your thinking is very open~

**Comment by ddliu** [comment]
@denjello I prefer something modern and flat. What do you think?

**Comment by denjello** [comment]
here is a totally different approach, based on the wonderful UML icons of facet and receptacle.
https://github.com/denjello/anyfs/blob/master/lib/assets/facetAndReceptacle

![anyfs_logo_terminaldosis](https://cloud.githubusercontent.com/assets/6129121/7337960/d8780fa4-ec3c-11e4-81d4-091007e6f72a.jpg)

**Comment by denjello** [comment]
And here is a one with thicker lines...

![anyfs_logo_terminaldosis_fat](https://cloud.githubusercontent.com/assets/6129121/7338052/ce91f6aa-ec3f-11e4-9811-f7992286b107.jpg)

**Comment by ddliu** [comment]
Aha, the thicker one looks better to me.

I like the idea!

As a logo, I think the horizontal line makes too much white space, what do you think?

**Comment by denjello** [comment]
I think that the length of the lines implies movement, like the "piping" of data from one place to another. I experimented with stubby lines, but they just looked wrong as soon as they were shorter than the circle was wide. Much longer, and they REALLY seemed to consume to much space. This design is the balance between the two.

And furthermore, a logo should have the power of using space on the screen.

**Comment by ddliu** [comment]
That's great!

How about a square version? We need it as the Github org icon.

Really appreciate for your contribution!

**Comment by denjello** [comment]
So I made you a new square version for the repo icon. Here it is. (I thinned the lines just a touch...)

![logo](https://raw.githubusercontent.com/denjello/anyfs/master/lib/assets/facetAndReceptacle/anyfs_logo_terminalDosis_med_SQUARE.jpg)

https://github.com/denjello/anyfs/blob/master/lib/assets/facetAndReceptacle/anyfs_logo_terminalDosis_med_SQUARE.jpg

**Comment by ddliu** [comment]
Uploaded the logo. Please let me know if you have any new ideas.

I have put you in the acknowledgement list, thank you!

**Comment by denjello** [comment]
my pleasure - and i will keep in touch. now just close this issue and get codin! ;)
